import { describe, expect, it } from 'vitest';
import {
  isTerminalIdentityResponse,
  isTerminalLocalInput,
  shouldSuppressTerminalInput,
} from '@frontend/utils/terminalInput';
import { fitTerminalSizeToPixels } from '@frontend/utils/terminalSizing';

describe('terminal sizing', () => {
  it('keeps configured dimensions when the pixel area can fit them', () => {
    expect(fitTerminalSizeToPixels(120, 40, 14, 2000, 900)).toEqual({ cols: 120, rows: 40 });
  });

  it('caps configured dimensions to the available pixel area', () => {
    const size = fitTerminalSizeToPixels(190, 44, 14, 780, 540);
    expect(size.cols).toBeLessThan(190);
    expect(size.rows).toBeLessThanOrEqual(44);
    expect(size.cols).toBeGreaterThanOrEqual(40);
    expect(size.rows).toBeGreaterThanOrEqual(10);
  });
});

describe('terminal input filtering', () => {
  it('detects terminal identity responses generated by xterm', () => {
    expect(isTerminalIdentityResponse('\x1b[>0;276;0c')).toBe(true);
    expect(isTerminalIdentityResponse('\x1b[?1;2c')).toBe(true);
    expect(isTerminalIdentityResponse('\x1b[c')).toBe(true);
  });

  it('does not treat visible text as a terminal identity response', () => {
    expect(isTerminalIdentityResponse('0;276;0c')).toBe(false);
    expect(isTerminalIdentityResponse('printf "\\x1b[>c"')).toBe(false);
  });

  it('suppresses OSC and CPR replies that break remote interactive prompts', () => {
    expect(shouldSuppressTerminalInput('\x1b]11;rgb:1e1e/1e1e/1e1e\x1b\\')).toBe(true);
    expect(shouldSuppressTerminalInput('\x1b[24;80R')).toBe(true);
    expect(shouldSuppressTerminalInput('\x1b[0n')).toBe(true);
  });

  it('does not suppress normal keyboard input', () => {
    expect(shouldSuppressTerminalInput('\x1b[A')).toBe(false);
    expect(shouldSuppressTerminalInput('hello')).toBe(false);
    expect(shouldSuppressTerminalInput('\r')).toBe(false);
  });
});

describe('terminal-local reports', () => {
  it('isolates mouse and focus reports without capturing keys or bracketed paste', () => {
    for (const value of ['\x1b[<35;6;1M', '\x1b[<0;6;1m', '\x1b[I', '\x1b[O']) {
      expect(isTerminalLocalInput(value)).toBe(true);
    }
    for (const value of ['k', '\x1b[A', '\x1b[200~\x1b[<35;6;1M\x1b[201~']) {
      expect(isTerminalLocalInput(value)).toBe(false);
    }
  });
});
