hosts:
  - id: example-host
    hostname: example.com
    port: 22
    username: ''
    tags:
      - linux
    mosh_allowed: false
  - id: 4de55209-4d7d-4695-8a5e-ba165ec45b35
    hostname: sparky.local
    port: 22
    username: jkh
    tags: []
    mosh_allowed: false
